name: Branch-Specific Workflow

on:
    pull_request:
        branches:
            - testing

jobs:
    testing-job:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: eu-west-2
            TELEGRAM_BOT_TOKEN: ${{ secrets.TESTING_BOT_TOKEN }}
            TELEGRAM_PROPOSAL_CHANNEL_ID: ${{ secrets.TESTING_PROPOSAL_CHANNEL_ID }}
            TELEGRAM_MEME_CHANNEL_ID: ${{ secrets.TESTING_MEME_CHANNEL_ID }}
        steps:
            - uses: actions/checkout@v3
            - name: Deploy to Testing
              run: |
                  npm install -g aws-cdk;
                  npm install;
                  cdk bootstrap;
                  cdk deploy --require-approval never;
